version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: quiz-nginx-dev
    ports:
      - '80:80'
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - api
    networks:
      - app-network

  frontend:
      image: node:24-alpine # Явно указываем образ, никаких build
      container_name: quiz-frontend-dev
      working_dir: /app
      volumes:
        - ./frontend:/app
        - frontend_node_modules:/app/node_modules
      ports:
        - '5173:5173'
      command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
      environment:
        - NODE_ENV=development
        - CHOKIDAR_USEPOLLING=true
      networks:
        - app-network
      stdin_open: true
      tty: true

  api:
    image: python:3.10-slim
    container_name: quiz-api-dev
    working_dir: /app
    volumes:
      - ./api:/app
      - ./api/tests.json:/app/tests.json
      - ./api/data:/app/data
    expose:
      - '8000'
    command: >
      sh -c "pip install -r requirements.txt && 
             uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - ENVIRONMENT=development
      - key_jwt=${key_jwt}
      - DATABASE_URL=sqlite:///./data/quiz.db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  frontend_node_modules: # Именованный том для node_modules