server {
    listen 80;
<<<<<<< HEAD
    server_name localhost;

=======
    server_name _;
>>>>>>> dabe19160952aef4e584cb1975c6f3e7410a64f5
    root /usr/share/nginx/html;
    index index.html;

    location / {
<<<<<<< HEAD
        try_files $uri $uri/ /index.html; # Для SPA (React/Vue/etc.)
    }

    # Gzip compression
    gzip on;
    gzip_types text/plain application/javascript application/x-javascript text/css application/xml text/javascript;
    gzip_min_length 1000;
=======
        try_files $uri $uri/ /index.html;
    }
>>>>>>> dabe19160952aef4e584cb1975c6f3e7410a64f5
}