import type { CompletionItem } from '@/types/coder'
export const CSS_PROPERTIES: CompletionItem[] = [
  { label: 'color',                type: 'property', description: 'Цвет текста' },
  { label: 'background',          type: 'property', description: 'Сокращённое свойство фона' },
  { label: 'background-color',    type: 'property', description: 'Цвет фона' },
  { label: 'background-image',    type: 'property', description: 'Фоновое изображение' },
  { label: 'background-size',     type: 'property', description: 'Размер фона' },
  { label: 'background-position', type: 'property', description: 'Позиция фона' },
  { label: 'font-size',           type: 'property', description: 'Размер шрифта' },
  { label: 'font-weight',         type: 'property', description: 'Жирность шрифта' },
  { label: 'font-family',         type: 'property', description: 'Гарнитура шрифта' },
  { label: 'font-style',          type: 'property', description: 'Начертание (italic/normal)' },
  { label: 'line-height',         type: 'property', description: 'Межстрочный интервал' },
  { label: 'letter-spacing',      type: 'property', description: 'Межбуквенное расстояние' },
  { label: 'text-align',          type: 'property', description: 'Горизонтальное выравнивание' },
  { label: 'text-decoration',     type: 'property', description: 'Оформление текста' },
  { label: 'text-transform',      type: 'property', description: 'Регистр букв' },
  { label: 'text-overflow',       type: 'property', description: 'Обрезка переполнения текста' },
  { label: 'white-space',         type: 'property', description: 'Обработка пробелов' },
  { label: 'word-break',          type: 'property', description: 'Перенос слов' },
  { label: 'margin',              type: 'property', description: 'Внешние отступы' },
  { label: 'margin-top',          type: 'property', description: 'Внешний отступ сверху' },
  { label: 'margin-bottom',       type: 'property', description: 'Внешний отступ снизу' },
  { label: 'margin-left',         type: 'property', description: 'Внешний отступ слева' },
  { label: 'margin-right',        type: 'property', description: 'Внешний отступ справа' },
  { label: 'padding',             type: 'property', description: 'Внутренние отступы' },
  { label: 'padding-top',         type: 'property', description: 'Внутренний отступ сверху' },
  { label: 'padding-bottom',      type: 'property', description: 'Внутренний отступ снизу' },
  { label: 'padding-left',        type: 'property', description: 'Внутренний отступ слева' },
  { label: 'padding-right',       type: 'property', description: 'Внутренний отступ справа' },
  { label: 'display',             type: 'property', description: 'Тип отображения' },
  { label: 'flex-direction',      type: 'property', description: 'Направление flex' },
  { label: 'flex-wrap',           type: 'property', description: 'Перенос flex-элементов' },
  { label: 'flex',                type: 'property', description: 'flex-grow/shrink/basis' },
  { label: 'flex-grow',           type: 'property', description: 'Коэффициент роста' },
  { label: 'flex-shrink',         type: 'property', description: 'Коэффициент сжатия' },
  { label: 'flex-basis',          type: 'property', description: 'Базовый размер' },
  { label: 'justify-content',     type: 'property', description: 'Выравнивание по главной оси' },
  { label: 'align-items',         type: 'property', description: 'Выравнивание по поперечной оси' },
  { label: 'align-self',          type: 'property', description: 'Выравнивание элемента' },
  { label: 'align-content',       type: 'property', description: 'Выравнивание строк flex' },
  { label: 'gap',                 type: 'property', description: 'Зазор между элементами' },
  { label: 'row-gap',             type: 'property', description: 'Зазор между строками' },
  { label: 'column-gap',          type: 'property', description: 'Зазор между колонками' },
  { label: 'grid-template-columns', type: 'property', description: 'Колонки grid' },
  { label: 'grid-template-rows',  type: 'property', description: 'Строки grid' },
  { label: 'grid-column',         type: 'property', description: 'Позиция по колонкам' },
  { label: 'grid-row',            type: 'property', description: 'Позиция по строкам' },
  { label: 'grid-area',           type: 'property', description: 'Область grid' },
  { label: 'width',               type: 'property', description: 'Ширина' },
  { label: 'height',              type: 'property', description: 'Высота' },
  { label: 'min-width',           type: 'property', description: 'Минимальная ширина' },
  { label: 'max-width',           type: 'property', description: 'Максимальная ширина' },
  { label: 'min-height',          type: 'property', description: 'Минимальная высота' },
  { label: 'max-height',          type: 'property', description: 'Максимальная высота' },
  { label: 'border',              type: 'property', description: 'Рамка (сокращение)' },
  { label: 'border-radius',       type: 'property', description: 'Скругление углов' },
  { label: 'border-color',        type: 'property', description: 'Цвет рамки' },
  { label: 'border-width',        type: 'property', description: 'Толщина рамки' },
  { label: 'border-style',        type: 'property', description: 'Стиль рамки' },
  { label: 'border-top',          type: 'property', description: 'Верхняя рамка' },
  { label: 'border-bottom',       type: 'property', description: 'Нижняя рамка' },
  { label: 'outline',             type: 'property', description: 'Внешняя обводка' },
  { label: 'box-shadow',          type: 'property', description: 'Тень блока' },
  { label: 'text-shadow',         type: 'property', description: 'Тень текста' },
  { label: 'transition',          type: 'property', description: 'Плавный переход' },
  { label: 'animation',           type: 'property', description: 'CSS-анимация' },
  { label: 'transform',           type: 'property', description: 'Трансформация' },
  { label: 'opacity',             type: 'property', description: 'Прозрачность (0–1)' },
  { label: 'visibility',          type: 'property', description: 'Видимость элемента' },
  { label: 'position',            type: 'property', description: 'Схема позиционирования' },
  { label: 'top',                 type: 'property', description: 'Отступ сверху' },
  { label: 'bottom',              type: 'property', description: 'Отступ снизу' },
  { label: 'left',                type: 'property', description: 'Отступ слева' },
  { label: 'right',               type: 'property', description: 'Отступ справа' },
  { label: 'z-index',             type: 'property', description: 'Порядок по оси Z' },
  { label: 'overflow',            type: 'property', description: 'Переполнение' },
  { label: 'overflow-x',          type: 'property', description: 'Горизонтальное переполнение' },
  { label: 'overflow-y',          type: 'property', description: 'Вертикальное переполнение' },
  { label: 'cursor',              type: 'property', description: 'Вид курсора' },
  { label: 'pointer-events',      type: 'property', description: 'События мыши' },
  { label: 'user-select',         type: 'property', description: 'Выделение текста' },
  { label: 'list-style',          type: 'property', description: 'Маркер списка' },
  { label: 'object-fit',          type: 'property', description: 'Масштаб img/video' },
  { label: 'object-position',     type: 'property', description: 'Позиция img/video' },
  { label: 'box-sizing',          type: 'property', description: 'Модель размеров' },
  { label: 'aspect-ratio',        type: 'property', description: 'Соотношение сторон' },
  { label: 'content',             type: 'property', description: 'Содержимое ::before/::after' },
  { label: 'resize',              type: 'property', description: 'Изменение размера' },
  { label: 'clip-path',           type: 'property', description: 'Фигурная обрезка' },
  { label: 'filter',              type: 'property', description: 'Графические фильтры' },
  { label: 'backdrop-filter',     type: 'property', description: 'Фильтр фона (blur и др.)' },
  { label: 'will-change',         type: 'property', description: 'Оптимизация анимации' },
  { label: 'scroll-behavior',     type: 'property', description: 'Плавный скролл' },
  { label: 'scroll-snap-type',    type: 'property', description: 'Прилипание при скролле' },
  { label: 'columns',             type: 'property', description: 'Многоколонная вёрстка' },
  { label: 'var',                 type: 'property', description: 'CSS-переменная: var(--name)' },
]

export const CSS_VALUES: Record<string, CompletionItem[]> = {
  display: [
    { label: 'block',        type: 'value', description: 'Блочный' },
    { label: 'inline',       type: 'value', description: 'Строчный' },
    { label: 'inline-block', type: 'value', description: 'Строчно-блочный' },
    { label: 'flex',         type: 'value', description: 'Flex-контейнер' },
    { label: 'inline-flex',  type: 'value', description: 'Строчный flex' },
    { label: 'grid',         type: 'value', description: 'Grid-контейнер' },
    { label: 'inline-grid',  type: 'value', description: 'Строчный grid' },
    { label: 'none',         type: 'value', description: 'Скрыть (убрать из потока)' },
    { label: 'contents',     type: 'value', description: 'Без бокса, только дети' },
    { label: 'table',        type: 'value', description: 'Как table' },
  ],
  position: [
    { label: 'static',   type: 'value', description: 'Нормальный поток (по умолч.)' },
    { label: 'relative', type: 'value', description: 'Относительное' },
    { label: 'absolute', type: 'value', description: 'Абсолютное' },
    { label: 'fixed',    type: 'value', description: 'Фиксированное (viewport)' },
    { label: 'sticky',   type: 'value', description: 'Прилипающее' },
  ],
  'justify-content': [
    { label: 'flex-start',    type: 'value', description: 'К началу' },
    { label: 'flex-end',      type: 'value', description: 'К концу' },
    { label: 'center',        type: 'value', description: 'По центру' },
    { label: 'space-between', type: 'value', description: 'Равные зазоры' },
    { label: 'space-around',  type: 'value', description: 'Равные отступы' },
    { label: 'space-evenly',  type: 'value', description: 'Идеально равные' },
    { label: 'start',         type: 'value', description: 'К началу контейнера' },
    { label: 'end',           type: 'value', description: 'К концу контейнера' },
  ],
  'align-items': [
    { label: 'stretch',    type: 'value', description: 'Растянуть (по умолч.)' },
    { label: 'flex-start', type: 'value', description: 'К началу поперечной оси' },
    { label: 'flex-end',   type: 'value', description: 'К концу поперечной оси' },
    { label: 'center',     type: 'value', description: 'По центру' },
    { label: 'baseline',   type: 'value', description: 'По базовой линии' },
  ],
  'flex-direction': [
    { label: 'row',            type: 'value', description: 'Слева направо' },
    { label: 'row-reverse',    type: 'value', description: 'Справа налево' },
    { label: 'column',         type: 'value', description: 'Сверху вниз' },
    { label: 'column-reverse', type: 'value', description: 'Снизу вверх' },
  ],
  'flex-wrap': [
    { label: 'nowrap',       type: 'value', description: 'Без переноса (по умолч.)' },
    { label: 'wrap',         type: 'value', description: 'С переносом' },
    { label: 'wrap-reverse', type: 'value', description: 'С переносом (обратный)' },
  ],
  overflow: [
    { label: 'visible', type: 'value', description: 'Видно за границами' },
    { label: 'hidden',  type: 'value', description: 'Обрезать' },
    { label: 'scroll',  type: 'value', description: 'Всегда скроллбар' },
    { label: 'auto',    type: 'value', description: 'Скроллбар при необходимости' },
    { label: 'clip',    type: 'value', description: 'Обрезать без скролла' },
  ],
  cursor: [
    { label: 'default',     type: 'value', description: 'Стандартный' },
    { label: 'pointer',     type: 'value', description: 'Рука (кликабельный)' },
    { label: 'text',        type: 'value', description: 'Текстовый' },
    { label: 'not-allowed', type: 'value', description: 'Запрещено' },
    { label: 'grab',        type: 'value', description: 'Захват' },
    { label: 'grabbing',    type: 'value', description: 'Захватывает' },
    { label: 'crosshair',   type: 'value', description: 'Прицел' },
    { label: 'move',        type: 'value', description: 'Перемещение' },
    { label: 'zoom-in',     type: 'value', description: 'Увеличение' },
    { label: 'zoom-out',    type: 'value', description: 'Уменьшение' },
    { label: 'none',        type: 'value', description: 'Скрыть' },
    { label: 'ew-resize',   type: 'value', description: 'Горизонтальное изменение' },
    { label: 'ns-resize',   type: 'value', description: 'Вертикальное изменение' },
  ],
  'object-fit': [
    { label: 'fill',       type: 'value', description: 'Растянуть' },
    { label: 'contain',    type: 'value', description: 'Вписать целиком' },
    { label: 'cover',      type: 'value', description: 'Заполнить с обрезкой' },
    { label: 'none',       type: 'value', description: 'Исходный размер' },
    { label: 'scale-down', type: 'value', description: 'Наименьший из contain/none' },
  ],
  'text-align': [
    { label: 'left',    type: 'value', description: 'По левому краю' },
    { label: 'right',   type: 'value', description: 'По правому краю' },
    { label: 'center',  type: 'value', description: 'По центру' },
    { label: 'justify', type: 'value', description: 'По ширине' },
    { label: 'start',   type: 'value', description: 'К началу (RTL-совместимо)' },
    { label: 'end',     type: 'value', description: 'К концу (RTL-совместимо)' },
  ],
  'box-sizing': [
    { label: 'content-box', type: 'value', description: 'padding вне width' },
    { label: 'border-box',  type: 'value', description: 'padding внутри width' },
  ],
  'font-weight': [
    { label: '100', type: 'value', description: 'Thin' },
    { label: '300', type: 'value', description: 'Light' },
    { label: '400', type: 'value', description: 'Regular' },
    { label: '500', type: 'value', description: 'Medium' },
    { label: '600', type: 'value', description: 'SemiBold' },
    { label: '700', type: 'value', description: 'Bold' },
    { label: '800', type: 'value', description: 'ExtraBold' },
    { label: '900', type: 'value', description: 'Black' },
    { label: 'normal', type: 'value', description: '= 400' },
    { label: 'bold',   type: 'value', description: '= 700' },
  ],
  'text-decoration': [
    { label: 'none',         type: 'value', description: 'Без оформления' },
    { label: 'underline',    type: 'value', description: 'Подчёркивание' },
    { label: 'line-through', type: 'value', description: 'Зачёркивание' },
    { label: 'overline',     type: 'value', description: 'Надчёркивание' },
  ],
  'text-transform': [
    { label: 'none',       type: 'value', description: 'Без изменений' },
    { label: 'uppercase',  type: 'value', description: 'ВСЕ ЗАГЛАВНЫЕ' },
    { label: 'lowercase',  type: 'value', description: 'все строчные' },
    { label: 'capitalize', type: 'value', description: 'Каждое Слово' },
  ],
  'white-space': [
    { label: 'normal',   type: 'value', description: 'Схлопывает пробелы' },
    { label: 'nowrap',   type: 'value', description: 'Без переноса' },
    { label: 'pre',      type: 'value', description: 'Как <pre>' },
    { label: 'pre-wrap', type: 'value', description: 'pre + перенос' },
    { label: 'pre-line', type: 'value', description: 'Схлопывает пробелы + перенос' },
  ],
  'border-style': [
    { label: 'none',   type: 'value', description: 'Без рамки' },
    { label: 'solid',  type: 'value', description: 'Сплошная' },
    { label: 'dashed', type: 'value', description: 'Штриховая' },
    { label: 'dotted', type: 'value', description: 'Точечная' },
    { label: 'double', type: 'value', description: 'Двойная' },
  ],
  visibility: [
    { label: 'visible',  type: 'value', description: 'Виден' },
    { label: 'hidden',   type: 'value', description: 'Невидим, занимает место' },
    { label: 'collapse', type: 'value', description: 'Схлопнуть (table)' },
  ],
  'background-size': [
    { label: 'cover',   type: 'value', description: 'Заполнить с обрезкой' },
    { label: 'contain', type: 'value', description: 'Вписать целиком' },
    { label: 'auto',    type: 'value', description: 'Исходный размер' },
    { label: '100%',    type: 'value', description: 'Ширина 100%' },
  ],
  'font-style': [
    { label: 'normal',  type: 'value', description: 'Обычный' },
    { label: 'italic',  type: 'value', description: 'Курсив' },
    { label: 'oblique', type: 'value', description: 'Наклонный' },
  ],
  'text-overflow': [
    { label: 'ellipsis', type: 'value', description: 'Многоточие при обрезке' },
    { label: 'clip',     type: 'value', description: 'Обрезать без символа' },
  ],
  'word-break': [
    { label: 'normal',     type: 'value', description: 'По умолчанию' },
    { label: 'break-all',  type: 'value', description: 'Разрывать в любом месте' },
    { label: 'keep-all',   type: 'value', description: 'Только между словами' },
    { label: 'break-word', type: 'value', description: 'По словам, потом по буквам' },
  ],
  'pointer-events': [
    { label: 'auto', type: 'value', description: 'Стандартно' },
    { label: 'none', type: 'value', description: 'Игнорировать события' },
  ],
  'user-select': [
    { label: 'auto',    type: 'value', description: 'Автоматически' },
    { label: 'none',    type: 'value', description: 'Нельзя выделить' },
    { label: 'text',    type: 'value', description: 'Только текст' },
    { label: 'all',     type: 'value', description: 'Весь блок целиком' },
  ],
  'scroll-behavior': [
    { label: 'auto',   type: 'value', description: 'Мгновенно' },
    { label: 'smooth', type: 'value', description: 'Плавно' },
  ],
  'will-change': [
    { label: 'transform', type: 'value', description: 'Оптимизировать transform' },
    { label: 'opacity',   type: 'value', description: 'Оптимизировать opacity' },
    { label: 'auto',      type: 'value', description: 'По умолчанию' },
  ],
}

export const CSS_SNIPPETS: CompletionItem[] = [
  {
    label: 'flex-center',
    type: 'snippet',
    description: 'Центрирование через flex',
    insertText: 'display: flex;\njustify-content: center;\nalign-items: center;',
  },
  {
    label: 'flex-between',
    type: 'snippet',
    description: 'Flex space-between + align center',
    insertText: 'display: flex;\njustify-content: space-between;\nalign-items: center;',
  },
  {
    label: 'reset',
    type: 'snippet',
    description: 'Универсальный CSS reset',
    insertText: '* {\n  margin: 0;\n  padding: 0;\n  box-sizing: border-box;\n}',
  },
  {
    label: 'abs-center',
    type: 'snippet',
    description: 'Абсолютное центрирование',
    insertText: 'position: absolute;\ntop: 50%;\nleft: 50%;\ntransform: translate(-50%, -50%);',
  },
  {
    label: 'grid-cols',
    type: 'snippet',
    description: 'Grid с 3 равными колонками',
    insertText: 'display: grid;\ngrid-template-columns: repeat(3, 1fr);\ngap: 1rem;',
  },
  {
    label: 'truncate',
    type: 'snippet',
    description: 'Обрезать текст многоточием',
    insertText: 'overflow: hidden;\nwhite-space: nowrap;\ntext-overflow: ellipsis;',
  },
  {
    label: 'full-page',
    type: 'snippet',
    description: 'На весь экран',
    insertText: 'width: 100vw;\nheight: 100vh;',
  },
  {
    label: 'transition-all',
    type: 'snippet',
    description: 'Плавный переход всех свойств',
    insertText: 'transition: all 0.3s ease;',
  },
]