import type { CompletionItem } from '@/types/coder'
export const HTML_TAGS: CompletionItem[] = [
  { label: 'div',      type: 'tag', description: 'Блочный контейнер' },
  { label: 'span',     type: 'tag', description: 'Строчный контейнер' },
  { label: 'a',        type: 'tag', description: 'Гиперссылка' },
  { label: 'img',      type: 'tag', description: 'Изображение (void)' },
  { label: 'input',    type: 'tag', description: 'Поле ввода (void)' },
  { label: 'button',   type: 'tag', description: 'Интерактивная кнопка' },
  { label: 'h1',       type: 'tag', description: 'Заголовок H1' },
  { label: 'h2',       type: 'tag', description: 'Заголовок H2' },
  { label: 'h3',       type: 'tag', description: 'Заголовок H3' },
  { label: 'h4',       type: 'tag', description: 'Заголовок H4' },
  { label: 'p',        type: 'tag', description: 'Абзац текста' },
  { label: 'ul',       type: 'tag', description: 'Маркированный список' },
  { label: 'ol',       type: 'tag', description: 'Нумерованный список' },
  { label: 'li',       type: 'tag', description: 'Элемент списка' },
  { label: 'nav',      type: 'tag', description: 'Блок навигации' },
  { label: 'header',   type: 'tag', description: 'Шапка страницы' },
  { label: 'footer',   type: 'tag', description: 'Подвал страницы' },
  { label: 'main',     type: 'tag', description: 'Основной контент' },
  { label: 'section',  type: 'tag', description: 'Тематическая секция' },
  { label: 'article',  type: 'tag', description: 'Самостоятельный блок' },
  { label: 'aside',    type: 'tag', description: 'Боковой контент' },
  { label: 'form',     type: 'tag', description: 'Форма' },
  { label: 'label',    type: 'tag', description: 'Подпись к полю' },
  { label: 'select',   type: 'tag', description: 'Выпадающий список' },
  { label: 'option',   type: 'tag', description: 'Элемент select' },
  { label: 'textarea', type: 'tag', description: 'Многострочный ввод' },
  { label: 'table',    type: 'tag', description: 'Таблица' },
  { label: 'thead',    type: 'tag', description: 'Шапка таблицы' },
  { label: 'tbody',    type: 'tag', description: 'Тело таблицы' },
  { label: 'tr',       type: 'tag', description: 'Строка таблицы' },
  { label: 'td',       type: 'tag', description: 'Ячейка таблицы' },
  { label: 'th',       type: 'tag', description: 'Заголовочная ячейка' },
  { label: 'style',    type: 'tag', description: 'Встроенные CSS-стили' },
  { label: 'script',   type: 'tag', description: 'Блок JavaScript' },
  { label: 'link',     type: 'tag', description: 'Внешний ресурс (void)' },
  { label: 'meta',     type: 'tag', description: 'Метаданные (void)' },
  { label: 'br',       type: 'tag', description: 'Перенос строки (void)' },
  { label: 'hr',       type: 'tag', description: 'Горизонтальная линия (void)' },
  { label: 'strong',   type: 'tag', description: 'Жирный текст' },
  { label: 'em',       type: 'tag', description: 'Курсивный текст' },
  { label: 'code',     type: 'tag', description: 'Строчный код' },
  { label: 'pre',      type: 'tag', description: 'Преформатированный текст' },
  { label: 'figure',   type: 'tag', description: 'Блок иллюстрации' },
  { label: 'video',    type: 'tag', description: 'Видео элемент' },
  { label: 'audio',    type: 'tag', description: 'Аудио элемент' },
  { label: 'canvas',   type: 'tag', description: 'Холст для рисования' },
  { label: 'svg',      type: 'tag', description: 'SVG-графика' },
]


export const GLOBAL_ATTRIBUTES: CompletionItem[] = [
  { label: 'class',        type: 'attribute', description: 'CSS-классы элемента' },
  { label: 'id',           type: 'attribute', description: 'Уникальный ID элемента' },
  { label: 'style',        type: 'attribute', description: 'Инлайн CSS-стили' },
  { label: 'src',          type: 'attribute', description: 'URL источника' },
  { label: 'href',         type: 'attribute', description: 'URL ссылки' },
  { label: 'type',         type: 'attribute', description: 'Тип элемента' },
  { label: 'placeholder',  type: 'attribute', description: 'Подсказка в поле ввода' },
  { label: 'value',        type: 'attribute', description: 'Значение элемента' },
  { label: 'name',         type: 'attribute', description: 'Имя в форме' },
  { label: 'disabled',     type: 'attribute', description: 'Отключить элемент' },
  { label: 'required',     type: 'attribute', description: 'Обязательное поле' },
  { label: 'target',       type: 'attribute', description: 'Где открыть ссылку' },
  { label: 'alt',          type: 'attribute', description: 'Альтернативный текст' },
  { label: 'rel',          type: 'attribute', description: 'Тип связи ресурса' },
  { label: 'action',       type: 'attribute', description: 'URL для отправки формы' },
  { label: 'method',       type: 'attribute', description: 'HTTP-метод формы' },
  { label: 'for',          type: 'attribute', description: 'Привязка label к input' },
  { label: 'checked',      type: 'attribute', description: 'Отмечен checkbox/radio' },
  { label: 'selected',     type: 'attribute', description: 'Выбранный option' },
  { label: 'colspan',      type: 'attribute', description: 'Объединение колонок' },
  { label: 'rowspan',      type: 'attribute', description: 'Объединение строк' },
  { label: 'data-',        type: 'attribute', description: 'Пользовательский data-атрибут' },
  { label: 'aria-label',   type: 'attribute', description: 'Доступное название' },
  { label: 'aria-hidden',  type: 'attribute', description: 'Скрыть от скринридеров' },
  { label: 'tabindex',     type: 'attribute', description: 'Порядок фокуса' },
  { label: 'width',        type: 'attribute', description: 'Ширина элемента' },
  { label: 'height',       type: 'attribute', description: 'Высота элемента' },
  { label: 'lang',         type: 'attribute', description: 'Язык содержимого' },
  { label: 'charset',      type: 'attribute', description: 'Кодировка (для meta)' },
  { label: 'content',      type: 'attribute', description: 'Содержимое meta' },
  { label: 'defer',        type: 'attribute', description: 'Отложить загрузку скрипта' },
  { label: 'async',        type: 'attribute', description: 'Асинхронная загрузка скрипта' },
  { label: 'crossorigin',  type: 'attribute', description: 'CORS-политика ресурса' },
  { label: 'loading',      type: 'attribute', description: 'Стратегия загрузки (lazy/eager)' },
  { label: 'decoding',     type: 'attribute', description: 'Стратегия декодирования img' },
  { label: 'autofocus',    type: 'attribute', description: 'Фокус при загрузке' },
  { label: 'autocomplete', type: 'attribute', description: 'Автозаполнение' },
  { label: 'readonly',     type: 'attribute', description: 'Только для чтения' },
  { label: 'max',          type: 'attribute', description: 'Максимальное значение' },
  { label: 'min',          type: 'attribute', description: 'Минимальное значение' },
  { label: 'step',         type: 'attribute', description: 'Шаг изменения значения' },
  { label: 'maxlength',    type: 'attribute', description: 'Максимум символов' },
  { label: 'pattern',      type: 'attribute', description: 'Regex-паттерн валидации' },
  { label: 'multiple',     type: 'attribute', description: 'Множественный выбор' },
  { label: 'open',         type: 'attribute', description: 'Раскрыть details/dialog' },
]


export const ATTR_VALUES: Record<string, CompletionItem[]> = {
  type: [
    { label: 'text',     type: 'value', description: 'Текстовое поле' },
    { label: 'password', type: 'value', description: 'Поле пароля' },
    { label: 'email',    type: 'value', description: 'Email с валидацией' },
    { label: 'number',   type: 'value', description: 'Числовое поле' },
    { label: 'tel',      type: 'value', description: 'Телефон' },
    { label: 'url',      type: 'value', description: 'URL-адрес' },
    { label: 'search',   type: 'value', description: 'Поле поиска' },
    { label: 'date',     type: 'value', description: 'Выбор даты' },
    { label: 'time',     type: 'value', description: 'Выбор времени' },
    { label: 'datetime-local', type: 'value', description: 'Дата и время' },
    { label: 'submit',   type: 'value', description: 'Кнопка отправки' },
    { label: 'button',   type: 'value', description: 'Обычная кнопка' },
    { label: 'reset',    type: 'value', description: 'Сброс формы' },
    { label: 'checkbox', type: 'value', description: 'Флажок' },
    { label: 'radio',    type: 'value', description: 'Радиокнопка' },
    { label: 'file',     type: 'value', description: 'Загрузка файла' },
    { label: 'hidden',   type: 'value', description: 'Скрытое поле' },
    { label: 'range',    type: 'value', description: 'Слайдер' },
    { label: 'color',    type: 'value', description: 'Цветовой пикер' },
  ],
  target: [
    { label: '_blank',  type: 'value', description: 'Новая вкладка' },
    { label: '_self',   type: 'value', description: 'Текущая вкладка' },
    { label: '_parent', type: 'value', description: 'Родительский фрейм' },
    { label: '_top',    type: 'value', description: 'Всё окно' },
  ],
  method: [
    { label: 'get',  type: 'value', description: 'Данные в URL' },
    { label: 'post', type: 'value', description: 'Данные в теле запроса' },
  ],
  rel: [
    { label: 'stylesheet', type: 'value', description: 'CSS-файл' },
    { label: 'noopener',   type: 'value', description: 'Безопасный target=_blank' },
    { label: 'noreferrer', type: 'value', description: 'Без Referer' },
    { label: 'icon',       type: 'value', description: 'Favicon' },
    { label: 'preload',    type: 'value', description: 'Предзагрузка' },
    { label: 'canonical',  type: 'value', description: 'Канонический URL' },
  ],
  loading: [
    { label: 'lazy',  type: 'value', description: 'Ленивая загрузка' },
    { label: 'eager', type: 'value', description: 'Немедленная загрузка' },
  ],
  autocomplete: [
    { label: 'on',    type: 'value', description: 'Включить автозаполнение' },
    { label: 'off',   type: 'value', description: 'Отключить автозаполнение' },
    { label: 'email', type: 'value', description: 'Email' },
    { label: 'name',  type: 'value', description: 'Полное имя' },
    { label: 'tel',   type: 'value', description: 'Телефон' },
    { label: 'url',   type: 'value', description: 'URL' },
  ],
  decoding: [
    { label: 'async', type: 'value', description: 'Асинхронное декодирование' },
    { label: 'sync',  type: 'value', description: 'Синхронное декодирование' },
    { label: 'auto',  type: 'value', description: 'Автоматически' },
  ],
}
