import type { CompletionItem } from '@/types/coder'
export const JS_KEYWORDS: CompletionItem[] = [
  { label: 'const',      type: 'keyword', description: 'Константа — нельзя переприсвоить' },
  { label: 'let',        type: 'keyword', description: 'Переменная с блочной областью' },
  { label: 'var',        type: 'keyword', description: 'Устаревшая переменная (function scope)' },
  { label: 'function',   type: 'keyword', description: 'Объявление функции' },
  { label: 'if',         type: 'keyword', description: 'Условный блок' },
  { label: 'else',       type: 'keyword', description: 'Альтернативный блок' },
  { label: 'for',        type: 'keyword', description: 'Цикл со счётчиком' },
  { label: 'while',      type: 'keyword', description: 'Цикл с условием' },
  { label: 'do',         type: 'keyword', description: 'do...while цикл' },
  { label: 'switch',     type: 'keyword', description: 'Множественное ветвление' },
  { label: 'case',       type: 'keyword', description: 'Ветка switch' },
  { label: 'break',      type: 'keyword', description: 'Выйти из цикла/switch' },
  { label: 'continue',   type: 'keyword', description: 'К следующей итерации' },
  { label: 'return',     type: 'keyword', description: 'Вернуть значение' },
  { label: 'async',      type: 'keyword', description: 'Асинхронная функция' },
  { label: 'await',      type: 'keyword', description: 'Ожидать Promise' },
  { label: 'class',      type: 'keyword', description: 'Объявление класса' },
  { label: 'extends',    type: 'keyword', description: 'Наследование класса' },
  { label: 'super',      type: 'keyword', description: 'Вызов родителя' },
  { label: 'new',        type: 'keyword', description: 'Создать экземпляр' },
  { label: 'this',       type: 'keyword', description: 'Текущий контекст' },
  { label: 'import',     type: 'keyword', description: 'Импорт модуля ES6' },
  { label: 'export',     type: 'keyword', description: 'Экспорт из модуля' },
  { label: 'default',    type: 'keyword', description: 'Дефолтный экспорт' },
  { label: 'try',        type: 'keyword', description: 'Блок try' },
  { label: 'catch',      type: 'keyword', description: 'Обработчик ошибки' },
  { label: 'finally',    type: 'keyword', description: 'Выполнить в любом случае' },
  { label: 'throw',      type: 'keyword', description: 'Выбросить ошибку' },
  { label: 'typeof',     type: 'keyword', description: 'Тип значения' },
  { label: 'instanceof', type: 'keyword', description: 'Принадлежность классу' },
  { label: 'delete',     type: 'keyword', description: 'Удалить свойство' },
  { label: 'null',       type: 'keyword', description: 'Отсутствие значения' },
  { label: 'undefined',  type: 'keyword', description: 'Не определено' },
  { label: 'true',       type: 'keyword', description: 'Булево: истина' },
  { label: 'false',      type: 'keyword', description: 'Булево: ложь' },
  { label: 'void',       type: 'keyword', description: 'Выражение без значения' },
  { label: 'in',         type: 'keyword', description: 'Проверить ключ в объекте' },
  { label: 'of',         type: 'keyword', description: 'Итерация значений' },
  { label: 'yield',      type: 'keyword', description: 'Пауза генератора' },
]

export const JS_METHODS: CompletionItem[] = [
  // console
  { label: 'console.log',     type: 'method', description: 'Вывод в консоль' },
  { label: 'console.warn',    type: 'method', description: 'Предупреждение' },
  { label: 'console.error',   type: 'method', description: 'Ошибка' },
  { label: 'console.table',   type: 'method', description: 'Таблица в консоли' },
  { label: 'console.group',   type: 'method', description: 'Сгруппировать вывод' },
  // document
  { label: 'document.getElementById',    type: 'method', description: 'Элемент по ID' },
  { label: 'document.querySelector',     type: 'method', description: 'Первый по CSS-селектору' },
  { label: 'document.querySelectorAll',  type: 'method', description: 'Все по CSS-селектору' },
  { label: 'document.createElement',    type: 'method', description: 'Создать DOM-элемент' },
  { label: 'document.createTextNode',    type: 'method', description: 'Создать текстовый узел' },
  { label: 'document.getElementById',   type: 'method', description: 'Получить по id' },
  // element events & dom
  { label: 'addEventListener',    type: 'method', description: 'Подписаться на событие' },
  { label: 'removeEventListener', type: 'method', description: 'Отписаться от события' },
  { label: 'dispatchEvent',       type: 'method', description: 'Вызвать событие вручную' },
  { label: 'appendChild',         type: 'method', description: 'Добавить дочерний узел' },
  { label: 'removeChild',         type: 'method', description: 'Удалить дочерний узел' },
  { label: 'insertBefore',        type: 'method', description: 'Вставить перед узлом' },
  { label: 'replaceChild',        type: 'method', description: 'Заменить дочерний узел' },
  { label: 'cloneNode',           type: 'method', description: 'Клонировать узел' },
  { label: 'closest',             type: 'method', description: 'Ближайший предок по селектору' },
  { label: 'matches',             type: 'method', description: 'Подходит ли CSS-селектор' },
  { label: 'contains',            type: 'method', description: 'Содержит ли узел' },
  { label: 'getBoundingClientRect', type: 'method', description: 'Координаты элемента' },
  { label: 'scrollIntoView',      type: 'method', description: 'Прокрутить к элементу' },
  { label: 'focus',               type: 'method', description: 'Установить фокус' },
  { label: 'blur',                type: 'method', description: 'Убрать фокус' },
  { label: 'click',               type: 'method', description: 'Симулировать клик' },
  // classList
  { label: 'classList.add',      type: 'method', description: 'Добавить класс' },
  { label: 'classList.remove',   type: 'method', description: 'Удалить класс' },
  { label: 'classList.toggle',   type: 'method', description: 'Переключить класс' },
  { label: 'classList.contains', type: 'method', description: 'Проверить наличие класса' },
  { label: 'classList.replace',  type: 'method', description: 'Заменить класс' },
  // attributes
  { label: 'setAttribute',  type: 'method', description: 'Установить атрибут' },
  { label: 'getAttribute',  type: 'method', description: 'Получить атрибут' },
  { label: 'removeAttribute', type: 'method', description: 'Удалить атрибут' },
  { label: 'hasAttribute',  type: 'method', description: 'Проверить атрибут' },
  { label: 'innerHTML',     type: 'method', description: 'HTML содержимое' },
  { label: 'textContent',   type: 'method', description: 'Текстовое содержимое' },
  { label: 'innerText',     type: 'method', description: 'Видимый текст' },
  // array
  { label: 'Array.from',    type: 'method', description: 'Массив из iterable' },
  { label: 'Array.isArray', type: 'method', description: 'Проверить массив' },
  { label: 'Array.of',      type: 'method', description: 'Массив из аргументов' },
  { label: 'forEach',       type: 'method', description: 'Перебрать массив' },
  { label: 'map',           type: 'method', description: 'Преобразовать элементы' },
  { label: 'filter',        type: 'method', description: 'Отфильтровать' },
  { label: 'reduce',        type: 'method', description: 'Свернуть в одно значение' },
  { label: 'reduceRight',   type: 'method', description: 'reduce справа налево' },
  { label: 'find',          type: 'method', description: 'Найти первый подходящий' },
  { label: 'findIndex',     type: 'method', description: 'Индекс первого подходящего' },
  { label: 'some',          type: 'method', description: 'Хотя бы один подходит' },
  { label: 'every',         type: 'method', description: 'Все подходят' },
  { label: 'includes',      type: 'method', description: 'Содержит значение' },
  { label: 'indexOf',       type: 'method', description: 'Индекс значения' },
  { label: 'push',          type: 'method', description: 'Добавить в конец' },
  { label: 'pop',           type: 'method', description: 'Убрать с конца' },
  { label: 'shift',         type: 'method', description: 'Убрать с начала' },
  { label: 'unshift',       type: 'method', description: 'Добавить в начало' },
  { label: 'splice',        type: 'method', description: 'Удалить/вставить' },
  { label: 'slice',         type: 'method', description: 'Извлечь часть' },
  { label: 'sort',          type: 'method', description: 'Сортировать' },
  { label: 'reverse',       type: 'method', description: 'Обратить порядок' },
  { label: 'join',          type: 'method', description: 'Объединить в строку' },
  { label: 'flat',          type: 'method', description: 'Распрямить вложенный' },
  { label: 'flatMap',       type: 'method', description: 'map + flat' },
  { label: 'fill',          type: 'method', description: 'Заполнить значением' },
  // object
  { label: 'Object.keys',    type: 'method', description: 'Ключи объекта' },
  { label: 'Object.values',  type: 'method', description: 'Значения объекта' },
  { label: 'Object.entries', type: 'method', description: 'Пары [ключ, значение]' },
  { label: 'Object.assign',  type: 'method', description: 'Слить объекты' },
  { label: 'Object.freeze',  type: 'method', description: 'Заморозить объект' },
  { label: 'Object.create',  type: 'method', description: 'Создать с прототипом' },
  { label: 'JSON.parse',     type: 'method', description: 'Разобрать JSON' },
  { label: 'JSON.stringify', type: 'method', description: 'Сериализовать в JSON' },
  // async / time
  { label: 'fetch',           type: 'method', description: 'HTTP-запрос (Promise)' },
  { label: 'Promise.all',     type: 'method', description: 'Дождаться всех' },
  { label: 'Promise.race',    type: 'method', description: 'Первый завершённый' },
  { label: 'Promise.resolve', type: 'method', description: 'Разрешённый Promise' },
  { label: 'Promise.reject',  type: 'method', description: 'Отклонённый Promise' },
  { label: 'setTimeout',      type: 'method', description: 'Задержка выполнения' },
  { label: 'setInterval',     type: 'method', description: 'Повторять с интервалом' },
  { label: 'clearTimeout',    type: 'method', description: 'Отменить setTimeout' },
  { label: 'clearInterval',   type: 'method', description: 'Остановить setInterval' },
  { label: 'requestAnimationFrame', type: 'method', description: 'Перед следующим кадром' },
  // string
  { label: 'split',       type: 'method', description: 'Разбить в массив' },
  { label: 'trim',        type: 'method', description: 'Убрать пробелы по краям' },
  { label: 'trimStart',   type: 'method', description: 'Убрать пробелы слева' },
  { label: 'trimEnd',     type: 'method', description: 'Убрать пробелы справа' },
  { label: 'replace',     type: 'method', description: 'Заменить первое вхождение' },
  { label: 'replaceAll',  type: 'method', description: 'Заменить все вхождения' },
  { label: 'startsWith',  type: 'method', description: 'Начинается ли' },
  { label: 'endsWith',    type: 'method', description: 'Заканчивается ли' },
  { label: 'toUpperCase', type: 'method', description: 'Верхний регистр' },
  { label: 'toLowerCase', type: 'method', description: 'Нижний регистр' },
  { label: 'padStart',    type: 'method', description: 'Дополнить слева' },
  { label: 'padEnd',      type: 'method', description: 'Дополнить справа' },
  { label: 'repeat',      type: 'method', description: 'Повторить N раз' },
  { label: 'charAt',      type: 'method', description: 'Символ по индексу' },
  { label: 'charCodeAt',  type: 'method', description: 'Код символа' },
  { label: 'substring',   type: 'method', description: 'Подстрока' },
  { label: 'lastIndexOf', type: 'method', description: 'Последнее вхождение' },
  { label: 'match',       type: 'method', description: 'Поиск по regex' },
  { label: 'matchAll',    type: 'method', description: 'Все совпадения regex' },
  { label: 'search',      type: 'method', description: 'Индекс по regex' },
  // math
  { label: 'Math.floor',  type: 'method', description: 'Округлить вниз' },
  { label: 'Math.ceil',   type: 'method', description: 'Округлить вверх' },
  { label: 'Math.round',  type: 'method', description: 'Ближайшее целое' },
  { label: 'Math.abs',    type: 'method', description: 'Абсолютное значение' },
  { label: 'Math.max',    type: 'method', description: 'Максимум' },
  { label: 'Math.min',    type: 'method', description: 'Минимум' },
  { label: 'Math.random', type: 'method', description: 'Случайное 0..1' },
  { label: 'Math.pow',    type: 'method', description: 'В степень' },
  { label: 'Math.sqrt',   type: 'method', description: 'Квадратный корень' },
  { label: 'Math.PI',     type: 'method', description: 'Число π' },
  // number
  { label: 'Number.parseInt',    type: 'method', description: 'Целое из строки' },
  { label: 'Number.parseFloat',  type: 'method', description: 'Дробное из строки' },
  { label: 'Number.isFinite',    type: 'method', description: 'Конечное число?' },
  { label: 'Number.isInteger',   type: 'method', description: 'Целое число?' },
  { label: 'Number.isNaN',       type: 'method', description: 'NaN?' },
  { label: 'toFixed',            type: 'method', description: 'N знаков после запятой' },
  // local storage
  { label: 'localStorage.setItem',    type: 'method', description: 'Сохранить в localStorage' },
  { label: 'localStorage.getItem',    type: 'method', description: 'Прочитать localStorage' },
  { label: 'localStorage.removeItem', type: 'method', description: 'Удалить из localStorage' },
  { label: 'localStorage.clear',      type: 'method', description: 'Очистить localStorage' },
]

export const JS_SNIPPETS: CompletionItem[] = [
  {
    label: 'log',
    type: 'snippet',
    description: 'console.log()',
    insertText: 'console.log($1);',
  },
  {
    label: 'func',
    type: 'snippet',
    description: 'Обычная функция',
    insertText: 'function $1($2) {\n  $3\n}',
  },
  {
    label: 'arrow',
    type: 'snippet',
    description: 'Стрелочная функция',
    insertText: 'const $1 = ($2) => {\n  $3\n};',
  },
  {
    label: 'afunc',
    type: 'snippet',
    description: 'Async стрелочная функция',
    insertText: 'const $1 = async ($2) => {\n  try {\n    $3\n  } catch (error) {\n    console.error(error);\n  }\n};',
  },
  {
    label: 'fetch',
    type: 'snippet',
    description: 'Fetch с async/await',
    insertText: "const response = await fetch('$1');\nif (!response.ok) throw new Error(`HTTP error: ${response.status}`);\nconst data = await response.json();\nconsole.log(data);",
  },
  {
    label: 'qs',
    type: 'snippet',
    description: 'document.querySelector',
    insertText: "const $1 = document.querySelector('$2');",
  },
  {
    label: 'qsa',
    type: 'snippet',
    description: 'document.querySelectorAll',
    insertText: "const $1 = document.querySelectorAll('$2');",
  },
  {
    label: 'ael',
    type: 'snippet',
    description: 'addEventListener',
    insertText: "$1.addEventListener('$2', (event) => {\n  $3\n});",
  },
  {
    label: 'cls',
    type: 'snippet',
    description: 'ES6 Class',
    insertText: 'class $1 {\n  constructor($2) {\n    $3\n  }\n\n  $4() {\n    $5\n  }\n}',
  },
  {
    label: 'trycatch',
    type: 'snippet',
    description: 'try/catch/finally',
    insertText: 'try {\n  $1\n} catch (error) {\n  console.error(error);\n} finally {\n  $2\n}',
  },
  {
    label: 'forin',
    type: 'snippet',
    description: 'for...in по ключам',
    insertText: 'for (const $1 in $2) {\n  if (Object.hasOwn($2, $1)) {\n    $3\n  }\n}',
  },
  {
    label: 'forof',
    type: 'snippet',
    description: 'for...of по значениям',
    insertText: 'for (const $1 of $2) {\n  $3\n}',
  },
  {
    label: 'iife',
    type: 'snippet',
    description: 'IIFE',
    insertText: "(function () {\n  'use strict';\n  $1\n})();",
  },
]
