FROM python:3.10-slim

WORKDIR /app

# Копируем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код
COPY . .

# Создаем папку для данных, если её нет
RUN mkdir -p /app/data

EXPOSE 8000

# Запускаем без --reload для продакшена
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]